### PR TITLE
Update gridsearch params and golden files.

### PR DESCRIPTION
**Pull request by peterthenelson**
What broke the tests this morning was:
- The change to the grid search params
- The change to the default of using a holdout (and the test invoking that)

This change reapplies your change to the gridsearch params, and it also changes the test to use
defaults for the holdout. Then I just updated the goldens, given that nothing looked crazy. I'll let
you decide on merging this.

### CODE REVIEW

**Comment by peterthenelson** [comment]
Yes / no?

**Comment by eli-s-goldberg** [comment]
"broke" may not be the right word, but I'll role with it. The grid search parameters are something that we need to be able to change. They should not be static. The approach is brute force, but it is important to generically tuning the model and to understand the explanatory power of the findings. Why don't we pass the grid search parameters in a tuple instead?

**Comment by peterthenelson** [comment]
When I said "broke", I'm not saying the behavior of your code was wrong, I
mean the test was broken by your change. The test is saying "I expect that
if I run the pipeline with these parameters, then I'll get this output". If
you're _intending_ to change the output with a change, then the testdata
needs to be updated, otherwise the test will break. If you're _not_
intending to change the output, then it provides assurance that you haven't
done so accidentally. It's generally helpful (when working with a test like
this) to break changes up into refactoring changes (potentially major code
changes, but no testdata change) and behavior changes (focused code
changes, testdata change to match new behavior).

In terms of passing the grid search params, I'd say that we probably need
to factor some of these parameters into config classes so that it's not a
huge list. Like, maybe a DatabaseConfig and some other config? _shrug_ I'll
think about it some more.

A few questions:
- Does the pre-commit hook work for you? (and other scripts)
- Some parts of the code suggest that this is supposed to work with
  databases other than the one provided. What exactly is required of a
  database for it to work with your software (ideally)? All the same columns?
  A superset of some required columns?

## \- What should I prioritize next?

**Comment by eli-s-goldberg** [comment]
A few questions:
- Does the pre-commit hook work for you? (and other scripts)
  *_Yes, but I'm not sure how to do this. I'll follow your lead here. *_
- Some parts of the code suggest that this is supposed to work with
  databases other than the one provided. What exactly is required of a
  database for it to work with your software (ideally)? All the same columns?
  The column names, as well as which columns are categorical variables, should be flagged. The categorical variables then need to be encoded [one-hot style](http://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.OneHotEncoder.html). In this doc, I've also got some lines where i drop columns that aren't necessary. This is typically required, as most databases have columns with too few data, which need to be removed, or aren't related to the actual data (e.g., publication title, authors, database notes, etc). 

A superset of some required columns?
- What should I prioritize next?
  Good question. The physicochemical conversion should be done before it's put into the main(). We should pull this out and fix up a script to run to convert features.

**Comment by peterthenelson** [comment]
Answers:
- Pre-commit hook: When you're in the main directory, in a shell:
  $ scripts/install_presubmit.sh
  This will make it so when you run git commit, it will first run the presubmit. Also, if you want to just run the presubmit or the tests or lint or whatever, you just run the appropriate script directly:
  $ script/run_tests.sh  # runs the tests
- For dropping columns, I can imagine two scenarios. Which do you want?:
  - We only support some predetermined columns. Anything else in your database gets dropped.
  - We will support any column unless you explicitly drop it. That column will be untransformed.

**Comment by peterthenelson** [comment]
And the last one:
- Yes, I agree that pulling out the conversions into separate code is a good idea and makes sense to approach soon.

**Pull request merged**
